openapi: 3.0.1
info:
  title: /
  version: 0.2.1
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /fhir/r4/Patient:
    get:
      operationId: getFhirR4Patient
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /fhir/r4/Patient/{id}:
    get:
      operationId: getFhirR4PatientId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
components: {}
